# Generated by Django 5.0.7 on 2024-07-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_name'),
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('name', 'city')},
        ),
    ]
